Bump to latest binutils==2.43
guedou/binutils-rs pull request #4
Opened 2024-09-01 17:39 UTC by CTM1

Changes:

- Bumped to 2.43, which required some modifications:
  - At one point, libbfd's `init_disassemble_info` started taking 4 arguments instead of 3. The 4th argument is a styled fprintf function, added a printf wrapper that ignores the style in the same fashion as (https://git.kernel.org/pub/scm/linux/kernel/git/bpf/bpf-next.git/commit/?id=600b7b26c07a070d0153daa76b3806c1e52c9e00).
  - Certain flag incompatibilities with later GCC versions (>10.something) required the `-fcommon` flag to avoid multiple definition errors. Added a `execute_with_env` function to the build script to accommodate this (https://github.com/easybuilders/easybuild-easyconfigs/issues/11988).
  - Updated the C examples. The documentation is outdated but I haven't had the time to update it. Had to modify the Makefile slightly to make them work
  - Linking `zstd` and `sframe` native libs on the build script.
  - Added checks to the C helpers and set default flavor to intel, this doesn't work for unsupported architectures like `mep` which still use AT&T syntax (who cares about `mep` anyway).
  - Valgrind warned about some uninitialized values in the `configure_disassemble_info_buffer` which caused some heisenbugs (worked when I printf the values to check them but SIGSEVd when I didn't)  so I modified the FFI and the helper function to take extra arguments and to properly initialize those values with zeroes. Same for the allocation helpers.
  - Small style changes suggested by the compiler to avoid warnings.
  
  I'm using this crate for a personal project and these modifications will do for now, I might add some more bindings in the future.

2024-09-10 09:57 UTC, CTM1 commented
Hello, is there anything missing you would like to see ?

2024-09-10 16:49 UTC, guedou commented
I should have answered earlier but I am super busy right now =\

I will need a bit more time to review your PR, but it looks great on my first overview.

I am really happy to read that you are using this crate!

2024-09-23 18:49 UTC, guedou requested changes
This looks good to me.  I made some minor comments.

2024-09-23 18:49 UTC, guedou commented on resources/README.md
> +**THIS IS OUTDATED**
```suggestion
**As of September 2024, the following documentation is outdated:**
```

2024-09-23 18:49 UTC, guedou commented on resources/examples/Makefile
> -# Copyright (C) 2018 Guillaume Valadon <guillaume@valadon.net>
Can you keep this line? You can add you name into `Cargo.toml`

2024-09-23 18:49 UTC, guedou commented on src/opcodes.rs
> +
Can you revert this change?

2024-09-23 18:49 UTC, guedou commented on src/opcodes.rs
> +
Can you revert this change?

2024-09-23 18:49 UTC, guedou commented on src/opcodes.rs
>                      "set_buffer() malloc error!".to_string(),
I
```suggestion
                    "helpers::configure_disassemble_info_buffer() malloc error!".to_string(),
```

2024-09-28 07:37 UTC, guedou approved these changes

2024-09-29 19:53 UTC, guedou commented
I had to apply the following patch to make it compile. Which rustc, architecture and OS are you using?

```
git diff src/bfd.rs
diff --git a/src/bfd.rs b/src/bfd.rs
index e2824f4..ee334d0 100644
--- a/src/bfd.rs
+++ b/src/bfd.rs
@@ -180,7 +180,7 @@ pub fn arch_list() -> Vec<String> {
                 stop = true;
                 break;
             }
-            let arch = unsafe { CStr::from_ptr(*item as *const i8).to_str() };
+            let arch = unsafe { CStr::from_ptr(*item as *const u8).to_str() };
             match arch {
                 Ok(s) => ret_vec.push(s.to_string()),
                 Err(_) => ret_vec.push("arch_list() - from_ptr() error !".to_string()),
```

2024-09-30 19:46 UTC, CTM1 commented
I've ran `cargo build` successfully in two different machines, both Linux, one ubuntu-based and another arch-based.

```
Pop!_OS 22.04 LTS x86_64

$ cargo -V
cargo 1.79.0 (ffa9cf99a 2024-06-03)                                               
$ rustc -V
rustc 1.79.0 (129f3b996 2024-06-10)
$ echo -n $TARGETS
$ %
```

```
EndeavourOS x86_64

$ cargo -V
cargo 1.80.1 (376290515 2024-07-16)
$ rustc -V
rustc 1.80.1 (3f5fd8dd4 2024-08-06)
$ echo -n $TARGETS
$ %
```

2024-09-30 19:53 UTC, CTM1 commented
I suppose on some systems, char in C is treated as signed while on others, it's unsigned, must be careful with this from now on...

Latest commit should fix the issue, lmk

2024-10-05 11:14 UTC, guedou reviewed
This looks good to me.

2024-10-05 11:17 UTC, guedou commented
This looks good to me but I still have an issue with the `build.rs` file on my aarch64 Ubuntu system. I will provide a fix.

Do you also have warnings? If yes, can you fix them.
```
$ cargo run --example test_buffer
warning: no edition set: defaulting to the 2015 edition while the latest is 2021
warning: binutils@0.1.1: src/helpers.c: In function ‘configure_disassemble_info’:
warning: binutils@0.1.1: src/helpers.c:134:70: warning: cast between incompatible function types from ‘void (*)(void *, enum disassembler_style,  const char *, ...)’ to ‘int (*)(void *, enum disassembler_style,  const char *, ...)’ [-Wcast-function-type]
warning: binutils@0.1.1:   134 |     init_disassemble_info(info, stdout, (fprintf_ftype) copy_buffer, (fprintf_styled_ftype) copy_buffer_styled);
warning: binutils@0.1.1:       |                                                                      ^
warning: binutils@0.1.1: src/helpers.c: In function ‘configure_disassemble_info_buffer’:
warning: binutils@0.1.1: src/helpers.c:161:70: warning: cast between incompatible function types from ‘void (*)(void *, enum disassembler_style,  const char *, ...)’ to ‘int (*)(void *, enum disassembler_style,  const char *, ...)’ [-Wcast-function-type]
warning: binutils@0.1.1:   161 |     init_disassemble_info(info, stdout, (fprintf_ftype) copy_buffer, (fprintf_styled_ftype) copy_buffer_styled);
warning: binutils@0.1.1:       |                                                                      ^
warning: binutils@0.1.1: src/helpers.c: In function ‘copy_buffer’:
warning: binutils@0.1.1: src/helpers.c:68:1: warning: control reaches end of non-void function [-Wreturn-type]
warning: binutils@0.1.1:    68 | }
warning: binutils@0.1.1:       | ^
```

2024-10-06 17:37 UTC, CTM1 commented
I don't have the warnings you've mentioned, could you give me your `rustc` version or any extra flags you're using in build so I can replicate ?
I've tried to provide a fix regardless

2024-10-09 18:19 UTC, guedou approved these changes

2024-10-09 18:22 UTC, guedou commented on build.rs
>      println!("cargo:rustc-link-search=native=/usr/lib/x86_64-linux-gnu/"); // Debian based
```suggestion
    println!("cargo:rustc-link-search=native=/usr/lib/{}-linux-gnu/", // Debian based
             env::var("CARGO_CFG_TARGET_ARCH").unwrap());
```

2024-10-09 18:22 UTC, guedou commented on src/helpers.c
> +    (void)useless;  // mark as unused
```suggestion
    (void) useless;  // mark as unused
```

2024-10-09 18:22 UTC, guedou commented on src/helpers.c
> +    (void)user_data;  // mark as unused
```suggestion
    (void) user_data;  // mark as unused
```

2024-10-09 18:22 UTC, guedou commented on src/helpers.c
> +    (void)style;
```suggestion
    (void) style;
```

2024-10-09 18:23 UTC, guedou commented on src/helpers.c
> +    init_disassemble_info(info, stdout, (fprintf_ftype) copy_buffer, copy_buffer_styled);
```suggestion
    init_disassemble_info (info, stdout, (fprintf_ftype) copy_buffer, copy_buffer_styled);
```

2024-10-09 18:23 UTC, guedou commented
Thanks! I made several modifications proposal. I think that we are ready for a release!

2024-10-27 13:20 UTC, CTM1 commented
Applied. Sorry that took so long, I've been quite busy
I'll be getting back to work on the library in the following weeks :)

2024-10-28 18:55 UTC, guedou commented
No problem ! Do you want me to merge this first part?

2024-10-31 12:50 UTC, CTM1 commented
LGTM, fire away

2024-11-08 18:29 UTC, merged

2024-11-08 18:30 UTC, guedou commented
Done!